# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_comapp', '0004_auto_20190502_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='e_comapp.CartItem'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
